# Generated by Django 5.2.16 on 2026-08-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
